name: Tests for Next.js app

on:
    pull_request:
        branches:
            - main
    push:

jobs:
    NextJS-Tests:
        name: Tests for Next.js app
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "20"

            - name: Install dependencies
              run: |
                  cd nextjs
                  npm install
                  npm install --save-dev ts-node typescript jest-environment-jsdom

            - name: Run Jest tests
              run: |
                  cd nextjs
                  npm test
